spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:fete;MODE=MySQL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      

jwt:
  header: ${JWT_HEADER:Authorization}
  secret: ${JWT_SECRET}
  # token-validity-in-seconds: ${JWT_TOKEN_VALIDITY_IN_SECONDS:86400}

admin:
  key: ${ADMIN_KEY}

toss:
  clientKey: ${TOSS_CLIENT_KEY}
  secretKey: ${TOSS_SECRET_KEY}
